- id:                     erth
  name:                   ErthPoint
  blockchain_key:         nem-testnet
  symbol:                 'Ł'
  type:                   coin
  precision:              8
  base_factor:            1_000_000
  enabled:                true
  # Deposits with less amount are skipped during blockchain synchronization.
  # We advise to set value 10 times bigger than the network fee to prevent losses.
  min_deposit_amount:     0.0001
  min_collection_amount:  0.0001
  withdraw_limit_24h:     0.5
  withdraw_limit_72h:     1.2
  deposit_fee:            0
  withdraw_fee:           0
  position:               1
  options:                {}
